Issue #6 patch applied
getDatabase() should return null as documented.

Instead it throws
net.sf.json.JSONException: JSONObject["error"] is not a JSONObject.
        at net.sf.json.JSONObject.getJSONObject(JSONObject.java:2139)
        at com.fourspaces.couchdb.CouchResponse.<init>(CouchResponse.java:90)

This is probably because CouchDB returns
{"error":"not_found","reason":"missing"}
where response["error"] is no JSONObject